### ISSUE TITLE
Feature_List container issues

### ISSUE THREAD

**Issue by suntnervos** [DATEx2/bike#3]
1. go to homepage
2. scroll down to the bottom of the page
3. observe the feature_list container

Expected results:
a. stick to the next container
b. should this menu and the footer be in view for the entire page/pages?
c. if there is a background/shadow it should be present for the entire menu - 
![image](https://github.com/DATEx2/bike/assets/171624523/cca74b34-43f7-48e7-acd9-8fd9bcc8391e)

Actual results:
a. a lot of space between this and the next container
b. provide answer
c. a background/shadow appear when a menu is reaching the left boundary of the screen (Money Back...)

**Comment by DATEx2** [comment]
Fixed
![image](https://github.com/DATEx2/bike/assets/83930915/c6d3dcd7-bb68-4cec-bc71-40c3a51eb255)
